spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddd_basic
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
  packages-to-scan: com.ddd.basic.api